export type CountryCode = {
  code: string; // dial code with +
  iso: string;
  name: string;
  flag: string;
};

export const COUNTRY_CODES: CountryCode[] = [
  { code: "+49", iso: "DE", name: "Alemania", flag: "🇩🇪" },
  { code: "+966", iso: "SA", name: "Arabia Saudita", flag: "🇸🇦" },
  { code: "+54", iso: "AR", name: "Argentina", flag: "🇦🇷" },
  { code: "+61", iso: "AU", name: "Australia", flag: "🇦🇺" },
  { code: "+43", iso: "AT", name: "Austria", flag: "🇦🇹" },
  { code: "+591", iso: "BO", name: "Bolivia", flag: "🇧🇴" },
  { code: "+55", iso: "BR", name: "Brasil", flag: "🇧🇷" },
  { code: "+32", iso: "BE", name: "Bélgica", flag: "🇧🇪" },
  { code: "+1", iso: "CA", name: "Canadá", flag: "🇨🇦" },
  { code: "+56", iso: "CL", name: "Chile", flag: "🇨🇱" },
  { code: "+86", iso: "CN", name: "China", flag: "🇨🇳" },
  { code: "+57", iso: "CO", name: "Colombia", flag: "🇨🇴" },
  { code: "+82", iso: "KR", name: "Corea del Sur", flag: "🇰🇷" },
  { code: "+506", iso: "CR", name: "Costa Rica", flag: "🇨🇷" },
  { code: "+53", iso: "CU", name: "Cuba", flag: "🇨🇺" },
  { code: "+45", iso: "DK", name: "Dinamarca", flag: "🇩🇰" },
  { code: "+593", iso: "EC", name: "Ecuador", flag: "🇪🇨" },
  { code: "+20", iso: "EG", name: "Egipto", flag: "🇪🇬" },
  { code: "+503", iso: "SV", name: "El Salvador", flag: "🇸🇻" },
  { code: "+971", iso: "AE", name: "Emiratos Árabes", flag: "🇦🇪" },
  { code: "+34", iso: "ES", name: "España", flag: "🇪🇸" },
  { code: "+1", iso: "US", name: "Estados Unidos", flag: "🇺🇸" },
  { code: "+63", iso: "PH", name: "Filipinas", flag: "🇵🇭" },
  { code: "+358", iso: "FI", name: "Finlandia", flag: "🇫🇮" },
  { code: "+33", iso: "FR", name: "Francia", flag: "🇫🇷" },
  { code: "+30", iso: "GR", name: "Grecia", flag: "🇬🇷" },
  { code: "+502", iso: "GT", name: "Guatemala", flag: "🇬🇹" },
  { code: "+509", iso: "HT", name: "Haití", flag: "🇭🇹" },
  { code: "+504", iso: "HN", name: "Honduras", flag: "🇭🇳" },
  { code: "+36", iso: "HU", name: "Hungría", flag: "🇭🇺" },
  { code: "+91", iso: "IN", name: "India", flag: "🇮🇳" },
  { code: "+62", iso: "ID", name: "Indonesia", flag: "🇮🇩" },
  { code: "+353", iso: "IE", name: "Irlanda", flag: "🇮🇪" },
  { code: "+972", iso: "IL", name: "Israel", flag: "🇮🇱" },
  { code: "+39", iso: "IT", name: "Italia", flag: "🇮🇹" },
  { code: "+81", iso: "JP", name: "Japón", flag: "🇯🇵" },
  { code: "+254", iso: "KE", name: "Kenia", flag: "🇰🇪" },
  { code: "+60", iso: "MY", name: "Malasia", flag: "🇲🇾" },
  { code: "+212", iso: "MA", name: "Marruecos", flag: "🇲🇦" },
  { code: "+52", iso: "MX", name: "México", flag: "🇲🇽" },
  { code: "+505", iso: "NI", name: "Nicaragua", flag: "🇳🇮" },
  { code: "+234", iso: "NG", name: "Nigeria", flag: "🇳🇬" },
  { code: "+47", iso: "NO", name: "Noruega", flag: "🇳🇴" },
  { code: "+64", iso: "NZ", name: "Nueva Zelanda", flag: "🇳🇿" },
  { code: "+507", iso: "PA", name: "Panamá", flag: "🇵🇦" },
  { code: "+595", iso: "PY", name: "Paraguay", flag: "🇵🇾" },
  { code: "+31", iso: "NL", name: "Países Bajos", flag: "🇳🇱" },
  { code: "+51", iso: "PE", name: "Perú", flag: "🇵🇪" },
  { code: "+48", iso: "PL", name: "Polonia", flag: "🇵🇱" },
  { code: "+351", iso: "PT", name: "Portugal", flag: "🇵🇹" },
  { code: "+1", iso: "PR", name: "Puerto Rico", flag: "🇵🇷" },
  { code: "+44", iso: "GB", name: "Reino Unido", flag: "🇬🇧" },
  { code: "+1", iso: "DO", name: "Rep. Dominicana", flag: "🇩🇴" },
  { code: "+420", iso: "CZ", name: "República Checa", flag: "🇨🇿" },
  { code: "+40", iso: "RO", name: "Rumania", flag: "🇷🇴" },
  { code: "+7", iso: "RU", name: "Rusia", flag: "🇷🇺" },
  { code: "+65", iso: "SG", name: "Singapur", flag: "🇸🇬" },
  { code: "+27", iso: "ZA", name: "Sudáfrica", flag: "🇿🇦" },
  { code: "+46", iso: "SE", name: "Suecia", flag: "🇸🇪" },
  { code: "+41", iso: "CH", name: "Suiza", flag: "🇨🇭" },
  { code: "+66", iso: "TH", name: "Tailandia", flag: "🇹🇭" },
  { code: "+90", iso: "TR", name: "Turquía", flag: "🇹🇷" },
  { code: "+380", iso: "UA", name: "Ucrania", flag: "🇺🇦" },
  { code: "+598", iso: "UY", name: "Uruguay", flag: "🇺🇾" },
  { code: "+58", iso: "VE", name: "Venezuela", flag: "🇻🇪" },
  { code: "+84", iso: "VN", name: "Vietnam", flag: "🇻🇳" },
];
