#!/usr/bin/env node
/**
 * Exports the CURRENT Supabase project so it can be replayed into a new one.
 *
 *   node scripts/export-db.mjs            # uses .env
 *   node scripts/export-db.mjs ./out-dir  # custom output directory
 *
 * Produces, in db-export/ :
 *   <table>.json          raw rows per public table
 *   import.sql            INSERT statements for every public table, in FK order
 *   auth-users.json       auth user records (metadata only — see note below)
 *   storage-manifest.json every stored file, with signed download URLs
 *   MANIFEST.md           row counts + what still needs doing by hand
 *
 * IMPORTANT — passwords: password hashes live in auth.users, which is not
 * reachable over the REST API. To carry logins across without forcing a reset
 * you need raw SQL on the source project (dashboard → SQL editor, or pg_dump
 * with the database password). See MIGRATION-RUNBOOK.md.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";

const OUT = process.argv[2] ?? "db-export";
mkdirSync(OUT, { recursive: true });

const env = Object.fromEntries(
  readFileSync(".env", "utf8")
    .split("\n")
    .filter((l) => l.includes("=") && !l.trim().startsWith("#"))
    .map((l) => {
      const i = l.indexOf("=");
      return [l.slice(0, i).trim(), l.slice(i + 1).trim().replace(/^"|"$/g, "")];
    }),
);
const URL_ = env.SUPABASE_URL;
const SVC = env.SUPABASE_SERVICE_ROLE_KEY;
if (!URL_ || !SVC) {
  console.error("Missing SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY in .env");
  process.exit(1);
}

const rt = {
  transport:
    typeof globalThis.WebSocket !== "undefined"
      ? globalThis.WebSocket
      : class {
          constructor() {
            throw new Error("no realtime");
          }
        },
};
const db = createClient(URL_, SVC, { auth: { persistSession: false }, realtime: rt });

// Parents before children so foreign keys resolve on import.
const TABLES = [
  "profiles",
  "user_roles",
  "leads",
  "calendar_events",
  "week_unlocks",
  "day_completions",
  "day_state",
  "week_state",
  "defi_results",
  "activity_results",
  "weekly_evaluations",
  "star_awards",
  "tutor_conversations",
  "tutor_usage",
  "suppressed_emails",
  "email_unsubscribe_tokens",
  "email_send_log",
  "email_send_state",
];

const lit = (v) => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "object") return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const counts = {};
const sql = [
  "-- Data import generated by scripts/export-db.mjs",
  "-- Apply AFTER all migrations have run on the target project.",
  "-- Triggers are disabled so star/award triggers don't double-fire on import.",
  "SET session_replication_role = replica;",
  "",
];

for (const t of TABLES) {
  const rows = [];
  const PAGE = 1000;
  for (let from = 0; ; from += PAGE) {
    const { data, error } = await db.from(t).select("*").range(from, from + PAGE - 1);
    if (error) {
      console.warn(`  ! ${t}: ${error.message} (skipped)`);
      break;
    }
    rows.push(...(data ?? []));
    if (!data || data.length < PAGE) break;
  }
  counts[t] = rows.length;
  writeFileSync(`${OUT}/${t}.json`, JSON.stringify(rows, null, 1));
  console.log(`  ${t}: ${rows.length}`);
  if (rows.length === 0) continue;
  const cols = Object.keys(rows[0]);
  sql.push(`-- ${t} (${rows.length})`);
  // Chunk so no single statement gets unwieldy.
  for (let i = 0; i < rows.length; i += 200) {
    const chunk = rows.slice(i, i + 200);
    sql.push(
      `INSERT INTO public.${t} (${cols.join(", ")}) VALUES\n` +
        chunk.map((r) => `(${cols.map((c) => lit(r[c])).join(",")})`).join(",\n") +
        "\nON CONFLICT DO NOTHING;",
    );
  }
  sql.push("");
}

sql.push("SET session_replication_role = DEFAULT;");
writeFileSync(`${OUT}/import.sql`, sql.join("\n"));

// Auth users (metadata only — hashes are not exposed over the admin API).
let users = [];
try {
  const res = await fetch(`${URL_}/auth/v1/admin/users?per_page=1000`, {
    headers: { Authorization: `Bearer ${SVC}`, apikey: SVC },
  });
  users = (await res.json()).users ?? [];
  writeFileSync(`${OUT}/auth-users.json`, JSON.stringify(users, null, 1));
  console.log(`  auth.users: ${users.length} (metadata only, no password hashes)`);
} catch (e) {
  console.warn("  ! auth users export failed:", e.message);
}

// Storage: list every object and mint download links.
const storage = [];
try {
  const { data: buckets } = await db.storage.listBuckets();
  for (const b of buckets ?? []) {
    const walk = async (prefix = "") => {
      const { data: entries } = await db.storage.from(b.id).list(prefix, { limit: 1000 });
      for (const e of entries ?? []) {
        const path = prefix ? `${prefix}/${e.name}` : e.name;
        if (e.id === null) await walk(path); // folder
        else {
          const { data: signed } = await db.storage.from(b.id).createSignedUrl(path, 60 * 60 * 24 * 7);
          storage.push({ bucket: b.id, path, size: e.metadata?.size ?? null, url: signed?.signedUrl ?? null });
        }
      }
    };
    await walk();
  }
  writeFileSync(`${OUT}/storage-manifest.json`, JSON.stringify(storage, null, 1));
  console.log(`  storage objects: ${storage.length}`);
} catch (e) {
  console.warn("  ! storage export failed:", e.message);
}

writeFileSync(
  `${OUT}/MANIFEST.md`,
  [
    `# Database export`,
    ``,
    `Source: ${URL_}`,
    `Taken: ${new Date().toISOString()}`,
    ``,
    `## Row counts`,
    ``,
    ...Object.entries(counts).map(([t, n]) => `- ${t}: ${n}`),
    `- auth.users: ${users.length}`,
    `- storage objects: ${storage.length}`,
    ``,
    `## Still needed by hand`,
    ``,
    `1. **Password hashes.** Not available over the API. Export auth.users with`,
    `   raw SQL on the source project, or every student must reset their password.`,
    `2. **Storage files.** Download via the signed URLs in storage-manifest.json`,
    `   (valid 7 days) and re-upload to the same paths on the target.`,
    `3. **Secrets.** OPENAI_API_KEY, RESEND_API_KEY and the new project's keys`,
    `   must be set on the target environment.`,
    ``,
  ].join("\n"),
);

console.log(`\nExport written to ${OUT}/`);
