/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Clase1RouteImport } from './routes/Clase1'
import { Route as ApoyoM1d11RouteImport } from './routes/apoyoM1d11'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as ConversationRouteImport } from './routes/conversation'
import { Route as DefiSemaine2RouteImport } from './routes/defi-semaine2'
import { Route as LiberteFrances98273425Plataforma834823RouteImport } from './routes/liberte-frances-98273425-plataforma-834823'
import { Route as LiberteLogIn983749824923465723RouteImport } from './routes/liberte-log-in-983749824923465723'
import { Route as LibertePlataforma834798234728482934254StudentRouteImport } from './routes/liberte-plataforma-834798234728482934254-student'
import { Route as LiberteProfesorPanel9382745AdminRouteImport } from './routes/liberte-profesor-panel-9382745-admin'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ClasesenvivoIndexRouteImport } from './routes/clasesenvivo.index'
import { Route as ClasesenvivoM1c1RouteImport } from './routes/clasesenvivo.m1c1'
import { Route as ClasesenvivoM1c2RouteImport } from './routes/clasesenvivo.m1c2'
import { Route as ClasesenvivoM1c3RouteImport } from './routes/clasesenvivo.m1c3'
import { Route as ClasesenvivoM1c4RouteImport } from './routes/clasesenvivo.m1c4'
import { Route as ClasesenvivoM1c5RouteImport } from './routes/clasesenvivo.m1c5'
import { Route as ClasesenvivoM1c6RouteImport } from './routes/clasesenvivo.m1c6'
import { Route as ClasesenvivoM1c7RouteImport } from './routes/clasesenvivo.m1c7'
import { Route as ClasesenvivoM1c8RouteImport } from './routes/clasesenvivo.m1c8'
import { Route as ClasesenvivoTaller1RouteImport } from './routes/clasesenvivo.taller1'
import { Route as DayDayIdRouteImport } from './routes/day.$dayId'
import { Route as SemaineWeekIdRouteImport } from './routes/semaine.$weekId'
import { Route as ApiPublicLiberteFrancesSignupRouteImport } from './routes/api/public/liberte-frances-signup'
import { Route as PlusWeekIdItemIdRouteImport } from './routes/plus.$weekId.$itemId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Clase1Route = Clase1RouteImport.update({
  id: '/Clase1',
  path: '/Clase1',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoyoM1d11Route = ApoyoM1d11RouteImport.update({
  id: '/apoyoM1d11',
  path: '/apoyoM1d11',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationRoute = ConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const DefiSemaine2Route = DefiSemaine2RouteImport.update({
  id: '/defi-semaine2',
  path: '/defi-semaine2',
  getParentRoute: () => rootRouteImport,
} as any)
const LiberteFrances98273425Plataforma834823Route =
  LiberteFrances98273425Plataforma834823RouteImport.update({
    id: '/liberte-frances-98273425-plataforma-834823',
    path: '/liberte-frances-98273425-plataforma-834823',
    getParentRoute: () => rootRouteImport,
  } as any)
const LiberteLogIn983749824923465723Route =
  LiberteLogIn983749824923465723RouteImport.update({
    id: '/liberte-log-in-983749824923465723',
    path: '/liberte-log-in-983749824923465723',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibertePlataforma834798234728482934254StudentRoute =
  LibertePlataforma834798234728482934254StudentRouteImport.update({
    id: '/liberte-plataforma-834798234728482934254-student',
    path: '/liberte-plataforma-834798234728482934254-student',
    getParentRoute: () => rootRouteImport,
  } as any)
const LiberteProfesorPanel9382745AdminRoute =
  LiberteProfesorPanel9382745AdminRouteImport.update({
    id: '/liberte-profesor-panel-9382745-admin',
    path: '/liberte-profesor-panel-9382745-admin',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasesenvivoIndexRoute = ClasesenvivoIndexRouteImport.update({
  id: '/clasesenvivo/',
  path: '/clasesenvivo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasesenvivoM1c1Route = ClasesenvivoM1c1RouteImport.update({
  id: '/clasesenvivo/m1c1',
  path: '/clasesenvivo/m1c1',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasesenvivoM1c2Route = ClasesenvivoM1c2RouteImport.update({
  id: '/clasesenvivo/m1c2',
  path: '/clasesenvivo/m1c2',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasesenvivoM1c3Route = ClasesenvivoM1c3RouteImport.update({
  id: '/clasesenvivo/m1c3',
  path: '/clasesenvivo/m1c3',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasesenvivoM1c4Route = ClasesenvivoM1c4RouteImport.update({
  id: '/clasesenvivo/m1c4',
  path: '/clasesenvivo/m1c4',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasesenvivoM1c5Route = ClasesenvivoM1c5RouteImport.update({
  id: '/clasesenvivo/m1c5',
  path: '/clasesenvivo/m1c5',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasesenvivoM1c6Route = ClasesenvivoM1c6RouteImport.update({
  id: '/clasesenvivo/m1c6',
  path: '/clasesenvivo/m1c6',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasesenvivoM1c7Route = ClasesenvivoM1c7RouteImport.update({
  id: '/clasesenvivo/m1c7',
  path: '/clasesenvivo/m1c7',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasesenvivoM1c8Route = ClasesenvivoM1c8RouteImport.update({
  id: '/clasesenvivo/m1c8',
  path: '/clasesenvivo/m1c8',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasesenvivoTaller1Route = ClasesenvivoTaller1RouteImport.update({
  id: '/clasesenvivo/taller1',
  path: '/clasesenvivo/taller1',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDayIdRoute = DayDayIdRouteImport.update({
  id: '/day/$dayId',
  path: '/day/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)
const SemaineWeekIdRoute = SemaineWeekIdRouteImport.update({
  id: '/semaine/$weekId',
  path: '/semaine/$weekId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiberteFrancesSignupRoute =
  ApiPublicLiberteFrancesSignupRouteImport.update({
    id: '/api/public/liberte-frances-signup',
    path: '/api/public/liberte-frances-signup',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlusWeekIdItemIdRoute = PlusWeekIdItemIdRouteImport.update({
  id: '/plus/$weekId/$itemId',
  path: '/plus/$weekId/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Clase1': typeof Clase1Route
  '/apoyoM1d11': typeof ApoyoM1d11Route
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRoute
  '/conversation': typeof ConversationRoute
  '/defi-semaine2': typeof DefiSemaine2Route
  '/liberte-frances-98273425-plataforma-834823': typeof LiberteFrances98273425Plataforma834823Route
  '/liberte-log-in-983749824923465723': typeof LiberteLogIn983749824923465723Route
  '/liberte-plataforma-834798234728482934254-student': typeof LibertePlataforma834798234728482934254StudentRoute
  '/liberte-profesor-panel-9382745-admin': typeof LiberteProfesorPanel9382745AdminRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clasesenvivo/m1c1': typeof ClasesenvivoM1c1Route
  '/clasesenvivo/m1c2': typeof ClasesenvivoM1c2Route
  '/clasesenvivo/m1c3': typeof ClasesenvivoM1c3Route
  '/clasesenvivo/m1c4': typeof ClasesenvivoM1c4Route
  '/clasesenvivo/m1c5': typeof ClasesenvivoM1c5Route
  '/clasesenvivo/m1c6': typeof ClasesenvivoM1c6Route
  '/clasesenvivo/m1c7': typeof ClasesenvivoM1c7Route
  '/clasesenvivo/m1c8': typeof ClasesenvivoM1c8Route
  '/clasesenvivo/taller1': typeof ClasesenvivoTaller1Route
  '/day/$dayId': typeof DayDayIdRoute
  '/semaine/$weekId': typeof SemaineWeekIdRoute
  '/clasesenvivo/': typeof ClasesenvivoIndexRoute
  '/api/public/liberte-frances-signup': typeof ApiPublicLiberteFrancesSignupRoute
  '/plus/$weekId/$itemId': typeof PlusWeekIdItemIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Clase1': typeof Clase1Route
  '/apoyoM1d11': typeof ApoyoM1d11Route
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRoute
  '/conversation': typeof ConversationRoute
  '/defi-semaine2': typeof DefiSemaine2Route
  '/liberte-frances-98273425-plataforma-834823': typeof LiberteFrances98273425Plataforma834823Route
  '/liberte-log-in-983749824923465723': typeof LiberteLogIn983749824923465723Route
  '/liberte-plataforma-834798234728482934254-student': typeof LibertePlataforma834798234728482934254StudentRoute
  '/liberte-profesor-panel-9382745-admin': typeof LiberteProfesorPanel9382745AdminRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clasesenvivo/m1c1': typeof ClasesenvivoM1c1Route
  '/clasesenvivo/m1c2': typeof ClasesenvivoM1c2Route
  '/clasesenvivo/m1c3': typeof ClasesenvivoM1c3Route
  '/clasesenvivo/m1c4': typeof ClasesenvivoM1c4Route
  '/clasesenvivo/m1c5': typeof ClasesenvivoM1c5Route
  '/clasesenvivo/m1c6': typeof ClasesenvivoM1c6Route
  '/clasesenvivo/m1c7': typeof ClasesenvivoM1c7Route
  '/clasesenvivo/m1c8': typeof ClasesenvivoM1c8Route
  '/clasesenvivo/taller1': typeof ClasesenvivoTaller1Route
  '/day/$dayId': typeof DayDayIdRoute
  '/semaine/$weekId': typeof SemaineWeekIdRoute
  '/clasesenvivo': typeof ClasesenvivoIndexRoute
  '/api/public/liberte-frances-signup': typeof ApiPublicLiberteFrancesSignupRoute
  '/plus/$weekId/$itemId': typeof PlusWeekIdItemIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Clase1': typeof Clase1Route
  '/apoyoM1d11': typeof ApoyoM1d11Route
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRoute
  '/conversation': typeof ConversationRoute
  '/defi-semaine2': typeof DefiSemaine2Route
  '/liberte-frances-98273425-plataforma-834823': typeof LiberteFrances98273425Plataforma834823Route
  '/liberte-log-in-983749824923465723': typeof LiberteLogIn983749824923465723Route
  '/liberte-plataforma-834798234728482934254-student': typeof LibertePlataforma834798234728482934254StudentRoute
  '/liberte-profesor-panel-9382745-admin': typeof LiberteProfesorPanel9382745AdminRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clasesenvivo/m1c1': typeof ClasesenvivoM1c1Route
  '/clasesenvivo/m1c2': typeof ClasesenvivoM1c2Route
  '/clasesenvivo/m1c3': typeof ClasesenvivoM1c3Route
  '/clasesenvivo/m1c4': typeof ClasesenvivoM1c4Route
  '/clasesenvivo/m1c5': typeof ClasesenvivoM1c5Route
  '/clasesenvivo/m1c6': typeof ClasesenvivoM1c6Route
  '/clasesenvivo/m1c7': typeof ClasesenvivoM1c7Route
  '/clasesenvivo/m1c8': typeof ClasesenvivoM1c8Route
  '/clasesenvivo/taller1': typeof ClasesenvivoTaller1Route
  '/day/$dayId': typeof DayDayIdRoute
  '/semaine/$weekId': typeof SemaineWeekIdRoute
  '/clasesenvivo/': typeof ClasesenvivoIndexRoute
  '/api/public/liberte-frances-signup': typeof ApiPublicLiberteFrancesSignupRoute
  '/plus/$weekId/$itemId': typeof PlusWeekIdItemIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Clase1'
    | '/apoyoM1d11'
    | '/calendar'
    | '/coach'
    | '/conversation'
    | '/defi-semaine2'
    | '/liberte-frances-98273425-plataforma-834823'
    | '/liberte-log-in-983749824923465723'
    | '/liberte-plataforma-834798234728482934254-student'
    | '/liberte-profesor-panel-9382745-admin'
    | '/profile'
    | '/progress'
    | '/reset-password'
    | '/clasesenvivo/m1c1'
    | '/clasesenvivo/m1c2'
    | '/clasesenvivo/m1c3'
    | '/clasesenvivo/m1c4'
    | '/clasesenvivo/m1c5'
    | '/clasesenvivo/m1c6'
    | '/clasesenvivo/m1c7'
    | '/clasesenvivo/m1c8'
    | '/clasesenvivo/taller1'
    | '/day/$dayId'
    | '/semaine/$weekId'
    | '/clasesenvivo/'
    | '/api/public/liberte-frances-signup'
    | '/plus/$weekId/$itemId'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Clase1'
    | '/apoyoM1d11'
    | '/calendar'
    | '/coach'
    | '/conversation'
    | '/defi-semaine2'
    | '/liberte-frances-98273425-plataforma-834823'
    | '/liberte-log-in-983749824923465723'
    | '/liberte-plataforma-834798234728482934254-student'
    | '/liberte-profesor-panel-9382745-admin'
    | '/profile'
    | '/progress'
    | '/reset-password'
    | '/clasesenvivo/m1c1'
    | '/clasesenvivo/m1c2'
    | '/clasesenvivo/m1c3'
    | '/clasesenvivo/m1c4'
    | '/clasesenvivo/m1c5'
    | '/clasesenvivo/m1c6'
    | '/clasesenvivo/m1c7'
    | '/clasesenvivo/m1c8'
    | '/clasesenvivo/taller1'
    | '/day/$dayId'
    | '/semaine/$weekId'
    | '/clasesenvivo'
    | '/api/public/liberte-frances-signup'
    | '/plus/$weekId/$itemId'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/Clase1'
    | '/apoyoM1d11'
    | '/calendar'
    | '/coach'
    | '/conversation'
    | '/defi-semaine2'
    | '/liberte-frances-98273425-plataforma-834823'
    | '/liberte-log-in-983749824923465723'
    | '/liberte-plataforma-834798234728482934254-student'
    | '/liberte-profesor-panel-9382745-admin'
    | '/profile'
    | '/progress'
    | '/reset-password'
    | '/clasesenvivo/m1c1'
    | '/clasesenvivo/m1c2'
    | '/clasesenvivo/m1c3'
    | '/clasesenvivo/m1c4'
    | '/clasesenvivo/m1c5'
    | '/clasesenvivo/m1c6'
    | '/clasesenvivo/m1c7'
    | '/clasesenvivo/m1c8'
    | '/clasesenvivo/taller1'
    | '/day/$dayId'
    | '/semaine/$weekId'
    | '/clasesenvivo/'
    | '/api/public/liberte-frances-signup'
    | '/plus/$weekId/$itemId'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Clase1Route: typeof Clase1Route
  ApoyoM1d11Route: typeof ApoyoM1d11Route
  CalendarRoute: typeof CalendarRoute
  CoachRoute: typeof CoachRoute
  ConversationRoute: typeof ConversationRoute
  DefiSemaine2Route: typeof DefiSemaine2Route
  LiberteFrances98273425Plataforma834823Route: typeof LiberteFrances98273425Plataforma834823Route
  LiberteLogIn983749824923465723Route: typeof LiberteLogIn983749824923465723Route
  LibertePlataforma834798234728482934254StudentRoute: typeof LibertePlataforma834798234728482934254StudentRoute
  LiberteProfesorPanel9382745AdminRoute: typeof LiberteProfesorPanel9382745AdminRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ClasesenvivoM1c1Route: typeof ClasesenvivoM1c1Route
  ClasesenvivoM1c2Route: typeof ClasesenvivoM1c2Route
  ClasesenvivoM1c3Route: typeof ClasesenvivoM1c3Route
  ClasesenvivoM1c4Route: typeof ClasesenvivoM1c4Route
  ClasesenvivoM1c5Route: typeof ClasesenvivoM1c5Route
  ClasesenvivoM1c6Route: typeof ClasesenvivoM1c6Route
  ClasesenvivoM1c7Route: typeof ClasesenvivoM1c7Route
  ClasesenvivoM1c8Route: typeof ClasesenvivoM1c8Route
  ClasesenvivoTaller1Route: typeof ClasesenvivoTaller1Route
  DayDayIdRoute: typeof DayDayIdRoute
  SemaineWeekIdRoute: typeof SemaineWeekIdRoute
  ClasesenvivoIndexRoute: typeof ClasesenvivoIndexRoute
  ApiPublicLiberteFrancesSignupRoute: typeof ApiPublicLiberteFrancesSignupRoute
  PlusWeekIdItemIdRoute: typeof PlusWeekIdItemIdRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Clase1': {
      id: '/Clase1'
      path: '/Clase1'
      fullPath: '/Clase1'
      preLoaderRoute: typeof Clase1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoyoM1d11': {
      id: '/apoyoM1d11'
      path: '/apoyoM1d11'
      fullPath: '/apoyoM1d11'
      preLoaderRoute: typeof ApoyoM1d11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation': {
      id: '/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof ConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defi-semaine2': {
      id: '/defi-semaine2'
      path: '/defi-semaine2'
      fullPath: '/defi-semaine2'
      preLoaderRoute: typeof DefiSemaine2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liberte-frances-98273425-plataforma-834823': {
      id: '/liberte-frances-98273425-plataforma-834823'
      path: '/liberte-frances-98273425-plataforma-834823'
      fullPath: '/liberte-frances-98273425-plataforma-834823'
      preLoaderRoute: typeof LiberteFrances98273425Plataforma834823RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liberte-log-in-983749824923465723': {
      id: '/liberte-log-in-983749824923465723'
      path: '/liberte-log-in-983749824923465723'
      fullPath: '/liberte-log-in-983749824923465723'
      preLoaderRoute: typeof LiberteLogIn983749824923465723RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liberte-plataforma-834798234728482934254-student': {
      id: '/liberte-plataforma-834798234728482934254-student'
      path: '/liberte-plataforma-834798234728482934254-student'
      fullPath: '/liberte-plataforma-834798234728482934254-student'
      preLoaderRoute: typeof LibertePlataforma834798234728482934254StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liberte-profesor-panel-9382745-admin': {
      id: '/liberte-profesor-panel-9382745-admin'
      path: '/liberte-profesor-panel-9382745-admin'
      fullPath: '/liberte-profesor-panel-9382745-admin'
      preLoaderRoute: typeof LiberteProfesorPanel9382745AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasesenvivo/': {
      id: '/clasesenvivo/'
      path: '/clasesenvivo'
      fullPath: '/clasesenvivo/'
      preLoaderRoute: typeof ClasesenvivoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasesenvivo/m1c1': {
      id: '/clasesenvivo/m1c1'
      path: '/clasesenvivo/m1c1'
      fullPath: '/clasesenvivo/m1c1'
      preLoaderRoute: typeof ClasesenvivoM1c1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasesenvivo/m1c2': {
      id: '/clasesenvivo/m1c2'
      path: '/clasesenvivo/m1c2'
      fullPath: '/clasesenvivo/m1c2'
      preLoaderRoute: typeof ClasesenvivoM1c2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasesenvivo/m1c3': {
      id: '/clasesenvivo/m1c3'
      path: '/clasesenvivo/m1c3'
      fullPath: '/clasesenvivo/m1c3'
      preLoaderRoute: typeof ClasesenvivoM1c3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasesenvivo/m1c4': {
      id: '/clasesenvivo/m1c4'
      path: '/clasesenvivo/m1c4'
      fullPath: '/clasesenvivo/m1c4'
      preLoaderRoute: typeof ClasesenvivoM1c4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasesenvivo/m1c5': {
      id: '/clasesenvivo/m1c5'
      path: '/clasesenvivo/m1c5'
      fullPath: '/clasesenvivo/m1c5'
      preLoaderRoute: typeof ClasesenvivoM1c5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasesenvivo/m1c6': {
      id: '/clasesenvivo/m1c6'
      path: '/clasesenvivo/m1c6'
      fullPath: '/clasesenvivo/m1c6'
      preLoaderRoute: typeof ClasesenvivoM1c6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasesenvivo/m1c7': {
      id: '/clasesenvivo/m1c7'
      path: '/clasesenvivo/m1c7'
      fullPath: '/clasesenvivo/m1c7'
      preLoaderRoute: typeof ClasesenvivoM1c7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasesenvivo/m1c8': {
      id: '/clasesenvivo/m1c8'
      path: '/clasesenvivo/m1c8'
      fullPath: '/clasesenvivo/m1c8'
      preLoaderRoute: typeof ClasesenvivoM1c8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasesenvivo/taller1': {
      id: '/clasesenvivo/taller1'
      path: '/clasesenvivo/taller1'
      fullPath: '/clasesenvivo/taller1'
      preLoaderRoute: typeof ClasesenvivoTaller1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$dayId': {
      id: '/day/$dayId'
      path: '/day/$dayId'
      fullPath: '/day/$dayId'
      preLoaderRoute: typeof DayDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semaine/$weekId': {
      id: '/semaine/$weekId'
      path: '/semaine/$weekId'
      fullPath: '/semaine/$weekId'
      preLoaderRoute: typeof SemaineWeekIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/liberte-frances-signup': {
      id: '/api/public/liberte-frances-signup'
      path: '/api/public/liberte-frances-signup'
      fullPath: '/api/public/liberte-frances-signup'
      preLoaderRoute: typeof ApiPublicLiberteFrancesSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus/$weekId/$itemId': {
      id: '/plus/$weekId/$itemId'
      path: '/plus/$weekId/$itemId'
      fullPath: '/plus/$weekId/$itemId'
      preLoaderRoute: typeof PlusWeekIdItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Clase1Route: Clase1Route,
  ApoyoM1d11Route: ApoyoM1d11Route,
  CalendarRoute: CalendarRoute,
  CoachRoute: CoachRoute,
  ConversationRoute: ConversationRoute,
  DefiSemaine2Route: DefiSemaine2Route,
  LiberteFrances98273425Plataforma834823Route:
    LiberteFrances98273425Plataforma834823Route,
  LiberteLogIn983749824923465723Route: LiberteLogIn983749824923465723Route,
  LibertePlataforma834798234728482934254StudentRoute:
    LibertePlataforma834798234728482934254StudentRoute,
  LiberteProfesorPanel9382745AdminRoute: LiberteProfesorPanel9382745AdminRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ClasesenvivoM1c1Route: ClasesenvivoM1c1Route,
  ClasesenvivoM1c2Route: ClasesenvivoM1c2Route,
  ClasesenvivoM1c3Route: ClasesenvivoM1c3Route,
  ClasesenvivoM1c4Route: ClasesenvivoM1c4Route,
  ClasesenvivoM1c5Route: ClasesenvivoM1c5Route,
  ClasesenvivoM1c6Route: ClasesenvivoM1c6Route,
  ClasesenvivoM1c7Route: ClasesenvivoM1c7Route,
  ClasesenvivoM1c8Route: ClasesenvivoM1c8Route,
  ClasesenvivoTaller1Route: ClasesenvivoTaller1Route,
  DayDayIdRoute: DayDayIdRoute,
  SemaineWeekIdRoute: SemaineWeekIdRoute,
  ClasesenvivoIndexRoute: ClasesenvivoIndexRoute,
  ApiPublicLiberteFrancesSignupRoute: ApiPublicLiberteFrancesSignupRoute,
  PlusWeekIdItemIdRoute: PlusWeekIdItemIdRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
