-- Week-4 lesson content (days 16-20) for the authoring system.
-- Day 16 from the detailed 'Prompt Lovable Día 16' spec; days 17-20 from the
-- Mes 1: J'OSE dictionary + curriculum. Idempotent: replaces days 16-20.

BEGIN;
DELETE FROM public.authored_days WHERE day_id BETWEEN 16 AND 20;

INSERT INTO public.authored_days (day_id, title, subtitle, status, created_by)
  VALUES (16, 'Jour 16 · Dans le vestiaire', 'Vêtements II — pronoms COD (le/la/les), ça me va, couleurs et probador', 'published', NULL);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (16, 10, 'text', $json${"title":"🎯 Objectif du jour","body":"Comentar cómo te queda algo (trop grand, ça me va), comparar prendas y decidir la compra usando los pronombres COD (le/la/les). Aprendes también los colores. (Situación: Tienda de ropa · Competencias DELF: CO + PO)"}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (16, 20, 'text', $json${"title":"📖 Grammaire — Pronoms COD : le / la / les","body":"En francés no repites el nombre de la prenda cuando ya se sabe de qué hablas: usas un pronombre COD.\n• LE = masculino singular → Je le prends. (le pantalon, le pull, le jean)\n• LA = femenino singular → Je la prends. (la robe, la veste, la chemise)\n• LES = plural → Je les prends. (les chaussures, les chemises)\n\n📌 Regla: el pronombre va SIEMPRE antes del verbo. Je le prends — nunca «je prends le».\n⚠️ En negación va entre NE y el verbo: Je ne le prends pas.\n\nEjemplos de tienda:\n• « Vous prenez ce pull ? » → « Oui, je le prends ! »\n• « Et cette robe ? » → « Non, je ne la prends pas, c'est trop cher. »\n• « Ces chaussures vous plaisent ? » → « Oui ! Je les prends. »"}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (16, 30, 'text', $json${"title":"📖 Grammaire — Ça me va (verbe ALLER, pas ÊTRE)","body":"« ÇA ME VA » es la frase del probador. Usa el verbo ALLER (ir/quedar/sentar), NO être. El vestido «va» = te favorece. Nunca se dice « c'est me va ».\n\nEstructura: ÇA (sujeto) + ME (pronombre) + VA (verbo aller).\n\n• Ça me va très bien. — Me queda muy bien.\n• Ça ne me va pas. — No me queda bien.\n• Ça vous va très bien ! — ¡Le queda muy bien! (el vendedor)\n• Ça me va parfaitement. — Me queda perfectamente.\n• Ça taille grand. — Talla grande → pide una talla menos.\n• Ça taille petit. — Talla pequeña → pide una talla más."}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (16, 40, 'text', $json${"title":"📖 Révision — Démonstratifs (ce / cet / cette / ces)","body":"El demostrativo SEÑALA; el pronombre COD REEMPLAZA. Trabajan juntos en la tienda:\n• ce + masc.: Ce pull me va très bien — je le prends !\n• cet + masc. con vocal: Cet imperméable est parfait — je le prends aussi.\n• cette + fem.: Cette robe me va parfaitement — je la prends !\n• ces + plural: Ces chaussures sont confortables — je les prends toutes !\n\n✅ Démonstratif para señalar · Pronom COD para reemplazar."}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (16, 50, 'vocab', $json${"items":[{"fr":"rouge","es":"rojo/a"},{"fr":"bleu / bleue","es":"azul"},{"fr":"vert / verte","es":"verde"},{"fr":"noir / noire","es":"negro/a"},{"fr":"blanc / blanche","es":"blanco/a"},{"fr":"gris / grise","es":"gris"},{"fr":"rose","es":"rosa (invariable)"},{"fr":"marron","es":"marrón / café (invariable)"},{"fr":"beige","es":"beige (invariable)"},{"fr":"orange","es":"naranja (invariable)"},{"fr":"violet / violette","es":"violeta / morado/a"},{"fr":"jaune","es":"amarillo/a"}]}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (16, 60, 'vocab', $json${"items":[{"fr":"ça me va","es":"me queda bien"},{"fr":"ça ne me va pas","es":"no me queda bien"},{"fr":"trop grand / grande","es":"demasiado grande"},{"fr":"trop petit / petite","es":"demasiado pequeño/a"},{"fr":"trop long / longue","es":"demasiado largo/a"},{"fr":"trop court / courte","es":"demasiado corto/a"},{"fr":"ça taille grand","es":"talla grande (pedir talla menos)"},{"fr":"ça taille petit","es":"talla pequeña (pedir talla más)"},{"fr":"parfait / parfaite","es":"perfecto/a"},{"fr":"l'échange","es":"el cambio"},{"fr":"le remboursement","es":"el reembolso"},{"fr":"le ticket de caisse","es":"el tiquete / el recibo"},{"fr":"en soldes","es":"de rebajas / en oferta"},{"fr":"la réduction","es":"el descuento"},{"fr":"la caisse","es":"la caja (pago)"},{"fr":"payer par carte","es":"pagar con tarjeta"},{"fr":"en espèces","es":"en efectivo"},{"fr":"la nouvelle collection","es":"la nueva colección"}]}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (16, 70, 'text', $json${"title":"🗝️ Expressions clés","body":"• Ça me va très bien ! Je la prends. — Me queda muy bien, me lo llevo.\n• C'est trop petit. Vous avez une taille au-dessus ? — Es muy pequeño, ¿tiene una talla más?\n• Ça taille grand — je prends du S en général.\n• Je voudrais faire un échange / un remboursement.\n• Je peux payer par carte ?"}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (16, 80, 'quiz', $json${"questions":[{"q":"J'aime beaucoup ce pull. Je ___ prends !","options":["la","le","les"],"correct":1},{"q":"Cette robe me va très bien. Je ___ prends.","options":["la","le","les"],"correct":0},{"q":"Ces chaussures sont parfaites. Je ___ prends !","options":["le","la","les"],"correct":2},{"q":"Ce manteau est magnifique. Je ___ prends.","options":["le","la","les"],"correct":0},{"q":"Cette veste ne me va pas. Je ne ___ prends pas.","options":["le","la","les"],"correct":1},{"q":"Ces chemises sont en soldes ! Je ___ prends toutes.","options":["le","la","les"],"correct":2}]}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (16, 90, 'quiz', $json${"questions":[{"q":"El vestido le queda perfectamente y decide comprarlo. ¿Qué dice?","options":["Ça ne me va pas.","Ça me va parfaitement ! Je la prends.","C'est trop grand."],"correct":1},{"q":"El pantalón le aprieta y necesita una talla más grande. ¿Qué dice?","options":["Ça me va très bien.","Ça taille grand.","C'est trop petit. Vous avez une taille au-dessus ?"],"correct":2},{"q":"La chaqueta es demasiado cara y no la compra. ¿Qué dice?","options":["Cette veste est trop chère. Je ne la prends pas.","Cette veste me va bien. Je la prends.","Je prends la veste — c'est bon marché."],"correct":0}]}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (16, 100, 'quiz', $json${"questions":[{"q":"¿Dónde va el pronombre COD en francés?","options":["Después del verbo","Antes del verbo","Al final de la frase","Después del sujeto"],"correct":1},{"q":"¿Cómo dices «me llevo el vestido» (robe = femenino)?","options":["Je le prends.","Je la prends.","Je les prends.","Je prends la."],"correct":1},{"q":"¿Qué significa «ça taille grand»?","options":["El vestido es muy grande.","Esta marca talla grande — necesitas una talla menos.","Hay que comprar una talla más.","La talla grande está agotada."],"correct":1},{"q":"El cliente dice «ça me va». ¿Qué verbo usa?","options":["Être","Aller","Avoir","Prendre"],"correct":1},{"q":"¿Cómo dices que no te llevas los zapatos (chaussures = plural)?","options":["Je ne le prends pas.","Je ne la prends pas.","Je ne les prends pas.","Je prends les pas."],"correct":2},{"q":"¿Cómo preguntas si puedes pagar con tarjeta?","options":["Vous payez par carte ?","Je peux payer par carte ?","Carte, s'il vous plaît.","C'est par carte ici ?"],"correct":1}]}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (16, 110, 'text', $json${"title":"💬 Dialogue modèle — Du vestiaire à la caisse","body":"Vendeur : Bonjour ! Je peux vous aider ?\nClient : Je voudrais essayer cette veste en noir, taille M.\nVendeur : Bien sûr. Les cabines sont au fond à droite.\nClient : C'est un peu trop grand. Vous avez en S ?\nVendeur : Voilà en S. Ça vous va mieux ?\nClient : Oui, ça me va parfaitement. C'est en soldes ?\nVendeur : Oui, 30% de réduction cette semaine.\nClient : Parfait ! Je la prends. Je peux payer par carte ?\nVendeur : Bien sûr. La caisse est à gauche."}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (16, 120, 'writing', $json${"title":"✍️ Production écrite — Le, la, les","prompt":"Escribe 4 frases usando los pronombres COD (le/la/les) para decir qué prendas te llevas y cuáles no (incluye una negación).","example":"Ce pull me plaît, je le prends. Cette robe est trop chère, je ne la prends pas. Ces chaussures sont parfaites, je les prends toutes ! Ce manteau est trop grand, je ne le prends pas."}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (16, 130, 'speaking', $json${"title":"🎙️ Production orale — Ma compra complète","prompt":"Enregistre-toi : entra a la tienda, pide probarte una prenda con talla y color, di cómo te queda (ça me va) y decide (je le/la/les prends). Termina preguntando cómo pagar.","example":"Bonjour ! Je voudrais essayer cette veste en taille M. … Ça me va très bien ! Je la prends. Je peux payer par carte ?"}$json$::jsonb);

INSERT INTO public.authored_days (day_id, title, subtitle, status, created_by)
  VALUES (17, 'Jour 17 · Au marché — les fruits', 'Marché I — expressions de quantité (un kilo de / une barquette de)', 'published', NULL);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (17, 10, 'text', $json${"title":"🎯 Objectif du jour","body":"Comprar frutas con cantidades (un kilo de, une barquette de) y preguntar si están frescas y de temporada. (Situación: Mercado · Competencias DELF: CO + PO)"}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (17, 20, 'text', $json${"title":"📖 Grammaire — Expressions de quantité","body":"Para comprar cantidades se usa un contenedor/medida + DE (¡sin artículo!): un kilo DE tomates, une barquette DE fraises, 500 grammes DE cerises, un bouquet DE persil.\n\n⚠️ El artículo desaparece después de la cantidad: NO «un kilo des tomates» ni «un kilo de les fraises».\n\nFórmula: contenedor + de + nom (sin artículo).\n\nEjemplos:\n• Un kilo de pommes, s'il vous plaît.\n• Une barquette de fraises. · 500 grammes de cerises.\n• C'est combien le kilo ? (¿Cuánto cuesta el kilo?)\n🔊 kilo [kilo] · barquette [baʁkɛt]"}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (17, 30, 'vocab', $json${"items":[{"fr":"un stand","es":"un puesto"},{"fr":"un marchand","es":"un vendedor de mercado"},{"fr":"un produit frais","es":"un producto fresco"},{"fr":"de saison","es":"de temporada"},{"fr":"une pomme","es":"una manzana"},{"fr":"une poire","es":"una pera"},{"fr":"une fraise","es":"una fresa"},{"fr":"une cerise","es":"una cereza"},{"fr":"une pêche","es":"un melocotón"},{"fr":"un abricot","es":"un albaricoque"},{"fr":"du raisin","es":"uvas"},{"fr":"un melon","es":"un melón"},{"fr":"une pastèque","es":"una sandía"},{"fr":"une orange","es":"una naranja"},{"fr":"un citron","es":"un limón"},{"fr":"une banane","es":"un plátano"},{"fr":"une mangue","es":"un mango"},{"fr":"un ananas","es":"una piña"},{"fr":"un avocat","es":"un aguacate"},{"fr":"mûr","es":"maduro"},{"fr":"un kilo de…","es":"un kilo de…"},{"fr":"500 grammes de…","es":"500 gramos de…"},{"fr":"une barquette de…","es":"una barqueta de…"},{"fr":"un bouquet de…","es":"un manojo de…"},{"fr":"C'est combien le kilo ?","es":"¿Cuánto cuesta el kilo?"},{"fr":"Donnez-moi…","es":"Deme…"},{"fr":"C'est frais d'aujourd'hui ?","es":"¿Es de hoy?"},{"fr":"un producteur local","es":"un productor local"},{"fr":"un étal","es":"un puesto de mercado"},{"fr":"une prune","es":"una ciruela"}]}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (17, 40, 'text', $json${"title":"🗝️ Expressions clés","body":"• C'est combien le kilo de tomates ? · Donnez-moi un kilo et demi.\n• Ces fraises sont de saison ? · C'est frais d'aujourd'hui ?\n• Une barquette de fraises, s'il vous plaît. · Un bouquet de persil."}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (17, 50, 'quiz', $json${"questions":[{"q":"«Un kilo de manzanas»:","options":["un kilo de pommes","un kilo des pommes","un kilo de les pommes"],"correct":0},{"q":"«¿Cuánto cuesta el kilo?»:","options":["C'est combien le kilo ?","C'est combien de kilo ?","Combien le kilo est ?"],"correct":0},{"q":"«Maduro»:","options":["mûr","frais","de saison"],"correct":0},{"q":"«Deme…»:","options":["Donnez-moi…","Donne-moi le…","Vous donnez…"],"correct":0},{"q":"«Una barqueta de fresas»:","options":["une barquette de fraises","une barquette des fraises","un barquette de fraise"],"correct":0}]}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (17, 60, 'writing', $json${"title":"✍️ Production écrite — Liste du marché","prompt":"Escribe una lista de compra del mercado con 5 frutas usando cantidades correctas (un kilo de…, une barquette de…, 500 grammes de…).","example":"Un kilo de pommes, une barquette de fraises, 500 grammes de cerises, deux bananes bien mûres et un melon."}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (17, 70, 'speaking', $json${"title":"🎙️ Production orale — Acheter des fruits","prompt":"Enregistre-toi en achetant 3 fruits avec les quantités, en demandant le prix au kilo et si c'est de saison.","example":"Bonjour, c'est combien le kilo de tomates ? Donnez-moi un kilo, s'il vous plaît. Et ces fraises, elles sont de saison ? Alors une barquette aussi."}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (17, 80, 'text', $json${"title":"💬 Dialogue modèle","body":"Client : Bonjour, c'est combien le kilo de tomates ?\nMarchand : 2 euros le kilo, madame.\nClient : Donnez-moi un kilo et demi, s'il vous plaît. Et vous avez du basilic frais ?\nMarchand : Oui, voilà. Un bouquet de basilic.\nClient : Parfait. Et ces fraises, elles sont de saison ?\nMarchand : Oui, elles arrivent ce matin.\nClient : Alors une barquette, s'il vous plaît. Ça fait combien en tout ?"}$json$::jsonb);

INSERT INTO public.authored_days (day_id, title, subtitle, status, created_by)
  VALUES (18, 'Jour 18 · Au marché — légumes & épices', 'Marché II — les articles partitifs (du / de la / des / de l'')', 'published', NULL);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (18, 10, 'text', $json${"title":"🎯 Objectif du jour","body":"Comprar verduras, hierbas y especias usando los artículos partitivos (du, de la, des, de l') en contexto real de compra. (Situación: Mercado · Competencias DELF: CE + PE)"}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (18, 20, 'text', $json${"title":"📖 Grammaire — Les articles partitifs","body":"Los partitivos expresan una cantidad indeterminada de algo:\n• du + masculino: du persil, du basilic.\n• de la + femenino: de la menthe, de la coriandre.\n• des + plural: des épinards, des haricots verts.\n• de l' + vocal / h muda: de l'ail, de l'eau.\n\n⚠️ No uses un/une con incontables: NO «un lait» → du lait.\n\nFórmula: du / de la / des / de l' + nom.\n🔊 du [dy] · de la [dəla] · des [de] · de l' [dəl]"}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (18, 30, 'vocab', $json${"items":[{"fr":"une tomate","es":"un tomate"},{"fr":"une carotte","es":"una zanahoria"},{"fr":"une pomme de terre","es":"una patata"},{"fr":"un oignon","es":"una cebolla"},{"fr":"de l'ail","es":"ajo"},{"fr":"une courgette","es":"un calabacín"},{"fr":"une aubergine","es":"una berenjena"},{"fr":"un poivron","es":"un pimiento"},{"fr":"un champignon","es":"un champiñón"},{"fr":"des épinards","es":"espinacas"},{"fr":"de la laitue","es":"lechuga"},{"fr":"du brocoli","es":"brócoli"},{"fr":"des haricots verts","es":"judías verdes"},{"fr":"des petits pois","es":"guisantes"},{"fr":"du maïs","es":"maíz"},{"fr":"du persil","es":"perejil"},{"fr":"du basilic","es":"albahaca"},{"fr":"de la coriandre","es":"cilantro"},{"fr":"de la menthe","es":"menta"},{"fr":"du gingembre","es":"jengibre"},{"fr":"du piment","es":"guindilla / ají picante"},{"fr":"une épice","es":"una especia"},{"fr":"une tranche de…","es":"una rebanada / rodaja de…"},{"fr":"un morceau de…","es":"un trozo de…"},{"fr":"du / de la / des / de l'","es":"artículos partitivos"},{"fr":"Il me faut…","es":"Necesito… / Me hace falta…"},{"fr":"C'est pour combien de personnes ?","es":"¿Para cuántas personas es?"},{"fr":"un poireau","es":"un puerro"},{"fr":"du chou","es":"col / repollo"},{"fr":"du thym","es":"tomillo"}]}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (18, 40, 'text', $json${"title":"🗝️ Expressions clés","body":"• Il me faut du persil et de l'ail. · Une tranche de melon.\n• Un morceau de fromage. · C'est pour combien de personnes ?\n• Du / de la / des / de l'."}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (18, 50, 'quiz', $json${"questions":[{"q":"«Ajo» (con partitivo):","options":["de l'ail","du ail","de la ail"],"correct":0},{"q":"«Espinacas»:","options":["des épinards","du épinards","de la épinards"],"correct":0},{"q":"«Necesito…»:","options":["Il me faut…","Il me faux…","Je me faut…"],"correct":0},{"q":"«Menta» (femenino):","options":["du menthe","de la menthe","des menthe"],"correct":1},{"q":"«Un trozo de queso»:","options":["un morceau de fromage","un morceau du fromage","un morceau des fromage"],"correct":0}]}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (18, 60, 'writing', $json${"title":"✍️ Production écrite — Liste d'ingrédients","prompt":"Escribe una lista de ingredientes para una receta usando los partitivos du / de la / des / de l'.","example":"Pour la recette, il me faut de l'ail, du persil, des tomates, de la coriandre et de l'huile d'olive."}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (18, 70, 'speaking', $json${"title":"🎙️ Production orale — Légumes et herbes","prompt":"Enregistre-toi en demandant des légumes et des herbes au marché avec les partitifs (dis pour combien de personnes tu cuisines).","example":"Bonjour, il me faut des courgettes, de l'ail et du basilic. C'est pour quatre personnes. Vous avez aussi de la menthe fraîche ?"}$json$::jsonb);

INSERT INTO public.authored_days (day_id, title, subtitle, status, created_by)
  VALUES (19, 'Jour 19 · À la salle de sport', 'Gym I — s''inscrire + verbes pronominaux (s''entraîner / se reposer)', 'published', NULL);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (19, 10, 'text', $json${"title":"🎯 Objectif du jour","body":"Inscribirse en un gimnasio, preguntar por tarifas, cursos y horarios, y hablar de objetivos deportivos con verbos pronominales. (Situación: Gimnasio · Competencias DELF: CO + PO)"}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (19, 20, 'text', $json${"title":"📖 Grammaire — Les verbes pronominaux","body":"Los verbos pronominales llevan un pronombre reflexivo (me/te/se…). Muy comunes para hablar de rutinas:\n• je me + verbe : je m'entraîne (me entreno), je me repose (descanso).\n• tu te + verbe : tu te muscles.\n• il/elle se + verbe : elle se repose.\n\n⚠️ No olvides el pronombre: NO «je entraîne» → je m'entraîne.\n\nEjemplos: s'entraîner (entrenarse), se reposer (descansar), se muscler (ganar músculo).\n🔊 je m'entraîne [ʒə mɑ̃tʁɛn] · se reposer [sərəpoze]"}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (19, 30, 'vocab', $json${"items":[{"fr":"une salle de sport","es":"un gimnasio"},{"fr":"un essai gratuit","es":"una prueba gratis"},{"fr":"une inscription","es":"una inscripción"},{"fr":"les frais d'inscription","es":"los gastos de inscripción"},{"fr":"mensuel","es":"mensual"},{"fr":"annuel","es":"anual"},{"fr":"un cours collectif","es":"una clase colectiva"},{"fr":"un coach sportif","es":"un entrenador personal"},{"fr":"un programme","es":"un programa"},{"fr":"une séance","es":"una sesión"},{"fr":"un entraînement","es":"un entrenamiento"},{"fr":"un échauffement","es":"un calentamiento"},{"fr":"un étirement","es":"un estiramiento"},{"fr":"le cardio","es":"el cardio"},{"fr":"la musculation","es":"la musculación"},{"fr":"le yoga","es":"el yoga"},{"fr":"le pilates","es":"el pilates"},{"fr":"la zumba","es":"la zumba"},{"fr":"la natation","es":"la natación"},{"fr":"un vestiaire","es":"un vestuario"},{"fr":"une douche","es":"una ducha"},{"fr":"un casier","es":"una taquilla"},{"fr":"une gourde","es":"una botella reutilizable"},{"fr":"une tenue de sport","es":"ropa deportiva"},{"fr":"un legging","es":"unas mallas"},{"fr":"un haltère","es":"una mancuerna"},{"fr":"un tapis de course","es":"una cinta de correr"},{"fr":"un vélo elliptique","es":"una bicicleta elíptica"},{"fr":"se muscler","es":"ganar músculo"},{"fr":"s'entraîner","es":"entrenarse"}]}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (19, 40, 'text', $json${"title":"🗝️ Expressions clés","body":"• Je voudrais m'inscrire. · Quel est le tarif ?\n• C'est inclus dans l'abonnement ? · Je m'entraîne trois fois par semaine.\n• Un cours collectif · un coach sportif · une séance."}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (19, 50, 'quiz', $json${"questions":[{"q":"«Me entreno»:","options":["je m'entraîne","je entraîne","j'entraîne me"],"correct":0},{"q":"«Quisiera inscribirme»:","options":["Je voudrais m'inscrire.","Je voudrais inscrire.","Je voudrais me inscrire."],"correct":0},{"q":"«Un abono mensual»:","options":["un abonnement mensuel","un abonnement annuel","une séance"],"correct":0},{"q":"«Descansar»:","options":["se reposer","se muscler","s'entraîner"],"correct":0},{"q":"«¿Está incluido en el abono?»:","options":["C'est inclus dans l'abonnement ?","C'est inclus dans l'abonné ?","Est inclus l'abonnement ?"],"correct":0}]}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (19, 60, 'writing', $json${"title":"✍️ Production écrite — Ma routine","prompt":"Escribe 4 frases sobre tu rutina deportiva usando verbos pronominales (s'entraîner, se reposer, se muscler, s'échauffer).","example":"Je m'entraîne trois fois par semaine. Je m'échauffe avant chaque séance. Je me muscle avec des haltères. Le week-end, je me repose."}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (19, 70, 'speaking', $json${"title":"🎙️ Production orale — S'inscrire à la salle","prompt":"Enregistre-toi en t'inscrivant à une salle de sport : demande le tarif, les horaires et ce qui est inclus.","example":"Bonjour, je voudrais m'inscrire. Quel est le tarif mensuel ? Les cours collectifs sont inclus dans l'abonnement ? Je m'entraîne trois fois par semaine."}$json$::jsonb);

INSERT INTO public.authored_days (day_id, title, subtitle, status, created_by)
  VALUES (20, 'Jour 20 · Objectifs & Défi final J''OSE', 'Gym II — verbes pronominaux + révision intégrée du mois J''OSE', 'published', NULL);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (20, 10, 'text', $json${"title":"🎯 Objectif du jour","body":"Hablar de tus objetivos y resultados deportivos, y completar el RETO FINAL J'OSE: integrar las 10 situaciones del mes en un audio/video real. (Situación: Gimnasio · Competencias DELF: las 4)"}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (20, 20, 'text', $json${"title":"📖 Révision intégrée — J'OSE","body":"Hoy repasas TODO el mes J'OSE. Recuerda las herramientas clave:\n• Je voudrais… (cortesía) · sans/avec · cantidades.\n• Il y a / il n'y a pas de · pour + infinitif · avoir mal à.\n• Comparatifs (plus/moins/aussi… que) · démonstratifs (ce/cette/ces).\n• Partitifs (du/de la/des) · verbes pronominaux (je me…).\n\nÚsalas todas juntas en situaciones reales: café, panadería, restaurante, supermercado, transporte, direcciones, farmacia, tienda, mercado y gimnasio."}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (20, 30, 'vocab', $json${"items":[{"fr":"se tonifier","es":"tonificarse"},{"fr":"perdre du poids","es":"perder peso"},{"fr":"prendre du muscle","es":"ganar músculo"},{"fr":"transpirer","es":"sudar"},{"fr":"se reposer","es":"descansar"},{"fr":"récupérer","es":"recuperarse"},{"fr":"progresser","es":"progresar"},{"fr":"s'améliorer","es":"mejorar"},{"fr":"se blesser","es":"lesionarse"},{"fr":"se dépasser","es":"superarse"},{"fr":"être en forme","es":"estar en forma"},{"fr":"tenir la forme","es":"mantenerse en forma"},{"fr":"se sentir bien","es":"sentirse bien"},{"fr":"être fatigué(e)","es":"estar cansado/a"},{"fr":"avoir des courbatures","es":"tener agujetas"},{"fr":"un objectif","es":"un objetivo"},{"fr":"un résultat","es":"un resultado"},{"fr":"la motivation","es":"la motivación"},{"fr":"un suivi","es":"un seguimiento"},{"fr":"un programme personnalisé","es":"un programa personalizado"},{"fr":"peser","es":"pesar"},{"fr":"souffler","es":"tomar aliento"},{"fr":"Je m'entraîne trois fois par semaine.","es":"Me entreno tres veces a la semana."},{"fr":"Je voudrais m'inscrire.","es":"Quisiera inscribirme."},{"fr":"C'est inclus dans l'abonnement ?","es":"¿Está incluido en el abono?"},{"fr":"Je veux me remettre en forme.","es":"Quiero ponerme en forma."},{"fr":"Quel est votre objectif ?","es":"¿Cuál es su objetivo?"},{"fr":"avoir la patate","es":"tener energía (informal)"},{"fr":"un bilan","es":"una evaluación"},{"fr":"Je fais du sport pour me sentir bien.","es":"Hago deporte para sentirme bien."}]}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (20, 40, 'text', $json${"title":"🗝️ Expressions clés","body":"• Je m'entraîne trois fois par semaine. · Je veux me remettre en forme.\n• Quel est votre objectif ? · C'est inclus dans l'abonnement ?\n• Je fais du sport pour me sentir bien."}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (20, 50, 'quiz', $json${"questions":[{"q":"«Ponerme en forma»:","options":["me remettre en forme","me reposer","me blesser"],"correct":0},{"q":"«Un objetivo»:","options":["un objectif","un résultat","un bilan"],"correct":0},{"q":"«Tener agujetas»:","options":["avoir des courbatures","être fatigué","transpirer"],"correct":0},{"q":"«Superarse»:","options":["se dépasser","se reposer","se peser"],"correct":0},{"q":"«Hago deporte para sentirme bien»:","options":["Je fais du sport pour me sentir bien.","Je fais le sport pour sentir bien.","Je fais du sport pour me sens bien."],"correct":0}]}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (20, 60, 'text', $json${"title":"🏆 Défi final du mois — J'ose vivre en français","body":"¡Felicidades! Llegas al reto final del Mes 1: J'OSE.\n\nGraba un audio o video de 3 a 5 minutos resolviendo 5 mini situaciones reales que mezclen los contextos del mes (por ejemplo: pedir en un café, comprar en el mercado, pedir indicaciones, describir un síntoma en la farmacia, inscribirte en el gimnasio).\n\nUsa las estructuras del mes: je voudrais, il y a, pour aller à, avoir mal à, comparatifs, partitifs, verbes pronominaux.\n\n🏅 Medalla: « Parisien(ne) accompli(e) » — Sais acheter, comparer et décider en français. Félicitations !\n\n💬 « La fluidez nace usando el idioma antes de sentirte listo/a. J'OSE ! »"}$json$::jsonb);
INSERT INTO public.authored_blocks (day_id, sort, type, payload)
  VALUES (20, 70, 'speaking', $json${"title":"🎙️ Reto final J'OSE — 5 situaciones reales","prompt":"Graba tu audio/video de 3-5 minutos resolviendo 5 situaciones reales del mes en francés (café, mercado, direcciones, farmacia, gimnasio). Aquí puedes practicar y grabar tu intento.","example":"Bonjour ! Je voudrais un café, s'il vous plaît. … Pour aller au marché, s'il vous plaît ? … Un kilo de pommes et une barquette de fraises. … J'ai mal à la tête depuis hier, qu'est-ce que vous me conseillez ? … Je voudrais m'inscrire à la salle de sport."}$json$::jsonb);

COMMIT;
