-- Mes 2 — the grammar points the client's Mapa specifies that were missing.
-- Adds them at the front of each day's grammar; nothing is removed.
-- Idempotent: re-running replaces the same days with the same content.

BEGIN;
UPDATE public.authored_days
   SET rich = jsonb_set(rich, '{grammar}', '[{"formula":"mon/ma/mes · ton/ta/tes · son/sa/ses · notre/nos · votre/vos · leur/leurs + nom","use":"El posesivo concuerda con el OBJETO POSEÍDO, no con quien posee: « ma mère » (madre, femenino) pero « mon père » (padre, masculino). C''est mon médecin. · C''est ma secrétaire. · Son numéro est le 06 12 34 56. · Nos voisins font du bruit. · Votre rendez-vous est confirmé. En un mensaje de voz los posesivos aparecen siempre."},{"formula":"mon + nom féminin commençant par une voyelle","use":"Excepción fonética: « mon amie », « mon adresse » — nunca « ma amie », solo para que suene bien. ⚠️ Error clásico: concordar con el poseedor → *ma père; lo correcto es mon père. Pronunciación: mon [mɔ̃] · ma [ma] · mes [me] · son [sɔ̃] · sa [sa] · notre [nɔtʁ] · votre [vɔtʁ]."},{"formula":"sujet + le/la/les + verbe conjugué","use":"El pronombre COD va SIEMPRE antes del verbo conjugado, nunca después: « Je rappelle Paul → Je le rappelle. » Error típico: « je rappelle le »."},{"formula":"je le + verbe (masculin singulier)","use":"« le » reemplaza un objeto directo masculino singular ya mencionado: « Tu as le numéro ? — Oui, je le note. »"},{"formula":"je la + verbe (féminin singulier)","use":"« la » reemplaza un objeto directo femenino singular: « Je rappelle Marie → Je la rappelle. »"},{"formula":"je les + verbe (pluriel) / le, la → l'' + voyelle","use":"« les » reemplaza un plural: « J''écoute les messages → Je les écoute. » Ante vocal, le/la se convierten en l'': « Je l''écoute »."}]'::jsonb)
 WHERE day_id = 23 AND rich IS NOT NULL;
UPDATE public.authored_days
   SET rich = jsonb_set(rich, '{grammar}', '[{"formula":"C''est + article + nom · C''est + adjectif · Il/Elle est + adjectif · Il/Elle est + profession (sans article)","use":"C''EST identifica y presenta: C''est l''appartement idéal. · C''est mon propriétaire. · C''est beau. IL/ELLE EST describe una característica: Il est très lumineux. · Elle est disponible le mois prochain. · Il est au 3e étage. Regla corta: después de un ARTÍCULO → c''est; con un adjetivo solo o una profesión → il/elle est."},{"formula":"Il est professeur (jamais « il est un professeur »)","use":"⚠️ Los tres errores clásicos: *Il est l''appartement → C''est l''appartement. · *Il est un professeur → Il est professeur (la profesión va SIN artículo). · Confundir c''est (presentar) con il est (describir). Pronunciación: c''est [sɛ] · il est [ilɛ] · elle est [ɛlɛ] · c''est beau [sɛbo]."},{"formula":"Objet : Demande d''information — …","use":"El asunto del correo formal: una línea breve y clara que anuncia el tema, antes del saludo. « Objet : Demande d''information — appartement rue Lepic »."},{"formula":"Bonjour Madame, / Bonjour Monsieur,","use":"La apertura formal obligatoria: nunca empieces con « salut » ni sin saludo, como en WhatsApp. « Bonjour Madame, je vous écris au sujet de l''appartement. »"},{"formula":"Je vous écris pour + infinitif / Je vous contacte au sujet de + nom","use":"El cuerpo del correo: anuncia el motivo con « vous » (registro formal). « Je vous contacte au sujet de l''appartement que vous proposez à la location. »"},{"formula":"Cordialement, + prénom et nom","use":"El cierre formal: una fórmula de despedida y tu nombre completo. « Dans l''attente de votre réponse, cordialement, Ana García. »"}]'::jsonb)
 WHERE day_id = 27 AND rich IS NOT NULL;
UPDATE public.authored_days
   SET rich = jsonb_set(rich, '{grammar}', '[{"formula":"Les 4 verbes piliers — être · avoir · faire · pouvoir","use":"ÊTRE: suis/es/est/sommes/êtes/sont — identidad y estado (Je suis client de la Banque de France). AVOIR: ai/as/a/avons/avez/ont — posesión (J''ai un compte courant). FAIRE: fais/fais/fait/faisons/faites/font — acciones (Je fais un virement de 200€). POUVOIR: peux/peux/peut/pouvons/pouvez/peuvent — posibilidad y permiso (Vous pouvez m''aider ?)."},{"formula":"avoir + sensation (jamais être)","use":"⚠️ El error que más delata: j''ai chaud (NO « je suis chaud ») · j''ai faim (NO « je suis faim ») · j''ai besoin de (NO « je suis besoin »). Y no confundas « je vais faire » (futur proche) con « je fais » (présent). Pronunciación: je suis [ʒəsɥi] · j''ai [ʒɛ] · je fais [ʒəfɛ] · je peux [ʒəpø] · nous pouvons [nupuvɔ̃]."},{"formula":"être + avoir = les auxiliaires du passé (Mes 3)","use":"Dominar estos cuatro ahora es la mejor inversión del mes: a partir del Mes 3, être y avoir se convierten en los auxiliares del passé composé. Todo el pasado del francés se apoya en ellos."},{"formula":"lui + verbe","use":"« Lui » reemplaza « à + una persona » (singular, hombre o mujer) y va ANTES del verbo: « Je parle au conseiller → Je lui parle. » / « J''écris à Marie → Je lui écris. »"},{"formula":"leur + verbe","use":"« Leur » reemplaza « à + varias personas » y también va antes del verbo: « J''écris aux voisins → Je leur écris. » / « Je téléphone à mes parents → Je leur téléphone. »"},{"formula":"ne + lui/leur + verbe + pas","use":"En la negación, el pronombre queda entre « ne » y el verbo: « Je ne lui donne pas mon code PIN. » / « Je ne leur réponds pas tout de suite. »"},{"formula":"lui/leur (COI) ≠ le/la (COD)","use":"Con verbos que llevan « à » (parler à, dire à, écrire à, demander à, donner à) usa lui/leur, no le/la: « Je lui dis bonjour » (correcto), « je le dis bonjour » (error)."}]'::jsonb)
 WHERE day_id = 31 AND rich IS NOT NULL;
UPDATE public.authored_days
   SET rich = jsonb_set(rich, '{grammar}', '[{"formula":"masc: adj · fém: adj+e · plur masc: adj+s · plur fém: adj+es","use":"El adjetivo concuerda en género y número: une robe bleue · des chaussures bleues. Irregulares que hay que saberse: beau→belle, nouveau→nouvelle, vieux→vieille, bon→bonne. Ante vocal, beau→bel: un bel article."},{"formula":"BAPNE + nom (l''adjectif AVANT le nom)","use":"Casi todos los adjetivos van DESPUÉS del nombre, pero los BAPNE van antes: Beau/Bon/Mauvais · Ancien/Autre · Petit/Premier/Prochain · Nouveau/Nombreux · Grand/Gros/Jeune/Joli/Long/Vieux. un beau manteau · une petite boutique · un bon prix · de nouveaux modèles · de vieilles chaussures."},{"formula":"couleurs composées = invariables","use":"⚠️ *un magasin grand → un grand magasin (BAPNE). *un beau homme → un bel homme (ante vocal). *une bonne prix → un bon prix (prix es masculino). Y los colores compuestos NO concuerdan: une robe bleu marine (nunca « bleue marine »). Pronunciación: beau [bo] · belle [bɛl] · bel [bɛl] · nouveau [nuvo] · nouvelle [nuvɛl] · vieux [vjø] · vieille [vjɛj] · bon [bɔ̃] · bonne [bɔn]."},{"formula":"Remplissez + nom","use":"El imperativo administrativo se forma con la 2.ª persona del plural: tomas el presente con « vous » (vous remplissez) y quitas el pronombre. Así dan órdenes los formularios: « Remplissez ce formulaire de retour. » (Rellene este formulario de devolución.)"},{"formula":"Signez / Cochez + complément","use":"Órdenes cortas típicas de un documento: firmar y marcar casillas. « Signez ici. » (Firme aquí.) « Cochez la case ''remboursement''. » (Marque la casilla ''reembolso''.) Se pronuncia cochez [koʃe]."},{"formula":"Joignez + les documents","use":"Imperativo de « joindre » para pedir adjuntar documentos: « Joignez les pièces justificatives. » (Adjunte los justificantes.) Error típico: usar el infinitivo como orden directa — « joindre les pièces » no es una instrucción."},{"formula":"Imprimez / Vérifiez + nom","use":"El mismo patrón (radical + -ez) funciona con cualquier verbo en -er: « Imprimez l''étiquette de retour. » (Imprima la etiqueta de devolución.) « Vérifiez votre adresse de facturation. » (Verifique su dirección de facturación.)"}]'::jsonb)
 WHERE day_id = 36 AND rich IS NOT NULL;
UPDATE public.authored_days
   SET rich = jsonb_set(rich, '{grammar}', '[{"formula":"sujet + verbe au PRÉSENT + depuis + durée","use":"La acción empezó en el pasado y CONTINÚA ahora, así que el francés usa PRESENTE donde el español dice « llevo… »: J''attends depuis 20 minutes. · Le train est en retard depuis midi. · On est ensemble depuis 3 ans. ⚠️ Jamás el pasado con depuis: *j''ai attendu depuis 20 minutes → j''attends depuis 20 minutes. No lo confundas con « il y a » (momento ya terminado)."},{"formula":"On + verbe à la 3e personne (= nous)","use":"« On » sustituye casi siempre a « nous » en la conversación oral — es lo natural, el francés vivo: On part demain matin. · Ça fait longtemps qu''on attend sur ce quai. ⚠️ On va SIEMPRE en singular: on part (nunca « on partons »). Pronunciación: depuis [dəpɥi] · on [ɔ̃] · ça fait [safɛ] · on attend [ɔ̃natɑ̃]."},{"formula":"Je voudrais savoir si / quand / où… (question indirecte)","use":"Preguntar con cortesía en la estación: « Je voudrais savoir si le train est à l''heure »."},{"formula":"ne… plus / ne… rien (négation avancée)","use":"« Il n''y a plus de places en première classe. » / « Je n''ai rien compris à l''annonce. »"},{"formula":"Compostez / Présentez / Validez (impératif des instructions)","use":"Instrucciones en la estación: « Compostez votre billet avant de monter à bord. »"},{"formula":"Le contrôleur dit que… (discours indirect)","use":"Reportar un anuncio: « Le contrôleur dit que le train part de la voie 3. »"}]'::jsonb)
 WHERE day_id = 39 AND rich IS NOT NULL;
UPDATE public.authored_days
   SET rich = jsonb_set(rich, '{grammar}', '[{"formula":"très / trop / assez / vraiment / plutôt + adjectif · verbe + beaucoup","use":"TRÈS = muy (neutro). TROP = demasiado, supera el límite (matiz negativo). ASSEZ = bastante/suficiente. VRAIMENT = de verdad (énfasis emocional). PLUTÔT = más bien (matiz de evaluación). Ce billet est très cher. · Ce siège est trop petit. · Je suis assez fatigué de ce voyage. · Elle est vraiment aimable. · C''est plutôt confortable."},{"formula":"beaucoup ne modifie JAMAIS un adjectif","use":"⚠️ *c''est beaucoup bien → c''est très bien. « Beaucoup » solo acompaña verbos: Il parle beaucoup, ce contrôleur ! · Tu travailles vraiment beaucoup. Ojo también con « c''est trop bien ! » (coloquial, oral) — en escrito formal usa très, y « c''est assez bon » puede sonar mediocre según el contexto. Pronunciación: très [tʁɛ] · trop [tʁo] · assez [ase] · beaucoup [boku] · vraiment [vʁɛmɑ̃] · plutôt [plyto]."},{"formula":"j''avais + participe passé","use":"El plus-que-parfait cuenta lo que había pasado ANTES de otro momento del pasado. Es clave para reclamar: « J''avais réservé ma place en ligne, mais j''ai raté mon train. »"},{"formula":"il/elle avait dit que + imparfait","use":"Discurso indirecto en pasado: reportas lo que alguien había dicho o explicado. « Elle avait expliqué que la correspondance était assurée. »"},{"formula":"d''abord… ensuite… enfin…","use":"Conectores para organizar los pasos de un trámite completo, como en el reto final: « D''abord j''appelle la gare, ensuite j''écris un e-mail, enfin je remplis le formulaire. »"},{"formula":"je viens de + infinitif / je vais + infinitif","use":"Pasado reciente y futuro próximo para gestionar un imprevisto sin cambiar al español: « Je viens de rater mon train, alors je vais rappeler le service clients. »"}]'::jsonb)
 WHERE day_id = 40 AND rich IS NOT NULL;
COMMIT;
